#!/bin/bash

echo "Compiling tests"
g++ -std=c++17 -c ./tests/GameFunctionTests.cpp ./src/GameUtility.cpp \
&& g++ ./*.o -o run_tests_bin \
&& rm ./*.o ./src/*.gch \

echo "Running tests as well"
./run_tests_bin

echo "Removing temporary file"
rm ./run_tests_bin
